version: "3.7"

services:
  gamba-api:
    image: ghcr.io/pokedex-gamba/gamba-api:latest
    ports:
      - "8889:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pokemon_gamba
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - POKEMON_API_URL=http://host.docker.internal:8888
      - INVENTORY_API_URL=http://host.docker.internal:8890
      - SELF_API_HOST=http://host.docker.internal:8889
    depends_on:
      - db
    volumes:
      - ./decoding_key:/decoding_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pokemon_gamba
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: